# Generated by Django 2.1.1 on 2019-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
