# Generated by Django 2.1.1 on 2019-10-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_choice_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rupees', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Food')),
            ],
        ),
    ]
