# Generated by Django 2.1.1 on 2019-10-06 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pub_dates',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date publish'),
        ),
    ]
